[project]
name = "codetanks-battlemaster"
version = "0.1.0"
requires-python = "~=3.13"
dependencies = [
    "dagger-io>=0.19.3",
    "jinja2>=3.1.6",
    "toml>=0.10.2",
]

[build-system]
requires = ["hatchling==1.28.0"]
build-backend = "hatchling.build"
